---
- name: install node and npm
  hosts: lockal
  become: yes
  tasks:
         - name: apt update repo and cache
           apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
         - name: install nodejs nad npm
           apt:
              pkg:
                - nodejs
                - npm
- name: deploy nodejs app
  hosts: lockal
  tasks:
          - name: Copy nodejs folder to a server
            copy: 
               src: /home/denis/node-project/app/bootcamp-node-project-1.0.0.tgz
               dest: /home/denis/app-1.0.0.tgz
          - name: unpack the nodejs file
            unarchive: 
               src: /home/denis/app-1.0.0.tgz
               dest: /home/denis/
               remote_src: yes
          - name: install npm
            npm:
              path: /home/denis/package
              
          - name: start the app
            command:
              chdir: /home/denis/ 
              cmd: node server
            async: 1000
            poll: 0
          - name: Ensure app is running
            shell: ps aux | grep node
            register: status_app
          - debug: msg={{status_app.stdout_lines}}   
