---
- name: create a user using a variable
  hosts: lockal
  vars:
    user: lisa
  tasks:
    - name: create a user {{user}} on host {{ ansilbe_hostname }}   
      user:
       name: "{{user}}"      
